# Dataframe

Es una estructura bidimensional

In [1]:
#importar librerias
import pandas as pd

# para saber la versión de pandas que se usa en colab
pd.__version__

'1.4.1'

In [2]:
# comando para actualizar la versión de pandas en colab
#!pip install --upgrade pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.3.5)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.21.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [2]:
pd.__version__

'1.4.1'

In [27]:
irregular_verbs = {
    "base" : ["arise", "awake","be","bear","beat"],
    "past" : ["arose", "awoke","was/were","bore","beat"],
    "participle" : ["arisen","awoken","been","born","beaten"]
}
irregular_verbs

{'base': ['arise', 'awake', 'be', 'bear', 'beat'],
 'participle': ['arisen', 'awoken', 'been', 'born', 'beaten'],
 'past': ['arose', 'awoke', 'was/were', 'bore', 'beat']}

In [28]:
# convertir el diccionario en dataframe
df = pd.DataFrame(irregular_verbs)
df

    base      past participle
0  arise     arose     arisen
1  awake     awoke     awoken
2     be  was/were       been
3   bear      bore       born
4   beat      beat     beaten

In [ ]:
# cambiar los indices

In [29]:
# checar los indices del dataframe
df.index

RangeIndex(start=0, stop=5, step=1)

In [30]:
# visualizar las columnas del dataframe
df.columns

Index(['base', 'past', 'participle'], dtype='object')

In [31]:
# visualizar los valores del dataframe
df.values

array([['arise', 'arose', 'arisen'],
       ['awake', 'awoke', 'awoken'],
       ['be', 'was/were', 'been'],
       ['bear', 'bore', 'born'],
       ['beat', 'beat', 'beaten']], dtype=object)

In [32]:
# visualizar los datos de una columna
# 1.nombre del dataframe, 2.corchetes, 3.nombre de la columna
df["past"]

0       arose
1       awoke
2    was/were
3        bore
4        beat
Name: past, dtype: object

In [33]:
df

    base      past participle
0  arise     arose     arisen
1  awake     awoke     awoken
2     be  was/were       been
3   bear      bore       born
4   beat      beat     beaten

In [34]:
# extraer datos a partir de un indice, o como mejor lo entiendo, sacar la info de un renglón, usando el comando loc
# [indice,['columna1','columna2'....]]
df.loc[2,['base', 'past', 'participle']]

base                be
past          was/were
participle        been
Name: 2, dtype: object

In [35]:
# extraer algunos datos del renglón
df.loc[2,['past']]

past    was/were
Name: 2, dtype: object

In [36]:
# extraer un dato en base a los indices usados como coordenadas, esto se hace con la función iloc
# digamos que se requiere el dato "awoke", que esta ubicado en el índice 1 y 1
df

    base      past participle
0  arise     arose     arisen
1  awake     awoke     awoken
2     be  was/were       been
3   bear      bore       born
4   beat      beat     beaten

In [37]:
df.iloc[1,1]

'awoke'

In [38]:
# extraer el dato en la posición 0,2
df.iloc[0,2]

'arisen'

In [40]:
# extraer datos de la primera y tercera columna sobre el indice 3
df.iloc[3,[0,2]]

base          bear
participle    born
Name: 3, dtype: object

In [41]:
# además se puede extraer datos de varios renglones y columnas
df.iloc[[0,2,3],[0,2]]

    base participle
0  arise     arisen
2     be       been
3   bear       born

In [43]:
# extraer la información de la columna entera
df.iloc[:,[0,2]]

    base participle
0  arise     arisen
1  awake     awoken
2     be       been
3   bear       born
4   beat     beaten

In [3]:
import numpy as np

In [4]:
dict_data = {
    'edad': [10,9,13,14,12,11,12],
    'cm': [115,110,130,155,125,120,125],
    'pais':['co','mx','co','mx','mx','ch','ch'],
    'genero':['M','F','F','M','M','M','F'],
    'Q1':[5,10,8,np.nan,7,8,3],
    'Q2':[7,9,9,8,8,8,9]
}
df2 = pd.DataFrame(dict_data)
df2

   edad   cm pais genero    Q1  Q2
0    10  115   co      M   5.0   7
1     9  110   mx      F  10.0   9
2    13  130   co      F   8.0   9
3    14  155   mx      M   NaN   8
4    12  125   mx      M   7.0   8
5    11  120   ch      M   8.0   8
6    12  125   ch      F   3.0   9

In [5]:
# Se puede filtrar la informacion con operadores
# por ejemplo filtrar el dataframe con las edade iguales o menores a 12
df2['edad'] <= 12

0     True
1     True
2    False
3    False
4     True
5     True
6     True
Name: edad, dtype: bool

In [50]:
df2[df2['edad'] <= 12]

   edad   cm pais genero    Q1  Q2
0    10  115   co      M   5.0   7
1     9  110   mx      F  10.0   9
4    12  125   mx      M   7.0   8
5    11  120   ch      M   8.0   8
6    12  125   ch      F   3.0   9

In [51]:
# se pueden combinar varias condiciones al mimo tiempo, separandolas por parentesis
# por ejemplo se requiere filtrar por personas menor a 12 años y que sean de México
df2[(df2['edad'] <= 12) & (df2['pais'] == 'mx')]

   edad   cm pais genero    Q1  Q2
1     9  110   mx      F  10.0   9
4    12  125   mx      M   7.0   8

In [53]:
# otra forma es usando querys
df2.query('edad <= 12')

   edad   cm pais genero    Q1  Q2
0    10  115   co      M   5.0   7
1     9  110   mx      F  10.0   9
4    12  125   mx      M   7.0   8
5    11  120   ch      M   8.0   8
6    12  125   ch      F   3.0   9

In [56]:
# comparación de valores entre dos columnas 
# por ejemplo filtrar la info de los estudiantes que mejoraron sus calificaciones en el Q2
# extraer algunos datos del renglón
df2[df2['Q2'] >= df2['Q1']]

   edad   cm pais genero   Q1  Q2
0    10  115   co      M  5.0   7
2    13  130   co      F  8.0   9
4    12  125   mx      M  7.0   8
5    11  120   ch      M  8.0   8
6    12  125   ch      F  3.0   9