# Manejo del formato Excel en Pandas.

## Importar y actualizar librerias

In [3]:
# importar librerias
import pandas as pd
import numpy as np

In [7]:
# actualizar la versión de "xlrd" en Colab
!pip install --upgrade xlrd

Requirement already satisfied: xlrd in /usr/local/lib/python3.7/dist-packages (1.1.0)
Collecting xlrd
  Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 4.0 MB/s
Installing collected packages: xlrd
  Attempting uninstall: xlrd
    Found existing installation: xlrd 1.1.0
    Uninstalling xlrd-1.1.0:
      Successfully uninstalled xlrd-1.1.0
Successfully installed xlrd-2.0.1

## Flujo para indexar y manejar archivos Excel, como crearlos y conectarse a Google Drive

1. Como conectar el ambiente de trabajo con la carpeta personal en Google Drive
2. Crear Dataframe
3. Crear archivo excel a partir del dataframe
4. Leer archivo .xls

## I. Como conectar el ambiente de trabajo con la carpeta personal en Google Drive

1. Abrir notebook
2. Importar la libreria "drive"
3. Ejecutar el comando drive.mount()
4. Ingresar credenciales de acceso
5. Ir a la cuenta de Drive 
6. Cambiar el directorio y posicionarse en la carpeta de Colab Notebooks
7. Listar el contenido de la carpeta

In [8]:
# 2.libreria de google
from google.colab import drive

In [9]:
# 3-4.ejecutar el comando  . . para . . 
drive.mount('/content/drive')

Mounted at /content/drive

5. Ir a la cuenta de Drive

In [10]:
# 6.Cambiar el directorio y posicionarse en la carpeta de Colab Notebooks
%cd '/content/drive/My Drive/Colab Notebooks'

/content/drive/My Drive/Colab Notebooks

In [11]:
# 7.listar el contenido de la carpeta
%ls

cadena_caracteres.ipynb        Operadores
Conversión_de_datos.ipynb      Platzi-courses/
db/                            Platzi_courses_data/
for.ipynb                      Python_print_variables.ipynb
introduccion_colab_live.ipynb  TestProject/
lava.jpg                       while.ipynb
Listas.ipynb

De esta forma, comprobamos que estamos ubicados en la carpeta de Colab Notebooks de Drive y se da por terminado el proceso de conexión al Google Drive

## II Crear Dataframe

1. Crear Diccionario
2. Convertir el diccionario a dataframe
3. Guardar el directorio donde se alamcenaran los archivos

In [12]:
#1. Crear un diccionario
dict_data = {
    'edad': [10,9,13,14,12,11,12],
    'cm': [115,110,130,155,125,120,125],
    'pais':['co','mx','co','mx','mx','ch','ch'],
    'genero':['M','F','F','M','M','M','F'],
    'Q1':[5,10,8,np.nan,7,8,3],
    'Q2':[7,9,9,8,8,8,9]
}

In [13]:
#2.convertir el diccionario a dataframe
df = pd.DataFrame(dict_data)
df

   edad   cm pais genero    Q1  Q2
0    10  115   co      M   5.0   7
1     9  110   mx      F  10.0   9
2    13  130   co      F   8.0   9
3    14  155   mx      M   NaN   8
4    12  125   mx      M   7.0   8
5    11  120   ch      M   8.0   8
6    12  125   ch      F   3.0   9

In [16]:
#3. Guardar el directorio donde se alamcenaran los archivos
#Guardar dataframe en Google Drive
#dir_pandas = "/content/drive/'My Drive'/'Colab Notebooks'/Platzi_courses_data/db/{}") #.format('test.csv')
dir_pandas = "/content/drive/My Drive/Colab Notebooks/Platzi_courses_data/db/{}" #).format('test.csv')
dir_pandas

'/content/drive/My Drive/Colab Notebooks/Platzi_courses_data/db/{}'

## III Crear archivo excel a partir del dataframe

In [17]:
# crear el archivo excel
df.to_excel(dir_pandas.format('test.xls'))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.

## IV Leer archivo de Excel

1. Leer archivo excel a partir de la variable
2. Leer archivo excel a partir de la ruta 
3. Retirar el index del archivo excel
4. Nombrar la hoja de excel

In [ ]:
# 1. Leer archivo excel a partir de la variable
pd.read_excel(dir_pandas.format('test.xls'))

In [ ]:
# 2. Leer archivo excel a partir de la ruta
pd.read_excel('/content/drive/My Drive/Colab Notebooks/Platzi_courses_data/db/test.xls')

In [19]:
# 3. retirar la columna Unnamed con la función index
df.to_excel(dir_pandas.format('test.xls'),index=False)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.

In [20]:
# leer un archivo excel sin la columna Unnamed
pd.read_excel(dir_pandas.format('test.xls'))

   edad   cm pais genero    Q1  Q2
0    10  115   co      M   5.0   7
1     9  110   mx      F  10.0   9
2    13  130   co      F   8.0   9
3    14  155   mx      M   NaN   8
4    12  125   mx      M   7.0   8
5    11  120   ch      M   8.0   8
6    12  125   ch      F   3.0   9

In [21]:
# 4. nombrar a la hoja de excel desde aqui
df.to_excel(dir_pandas.format('test.xls'),index=False,sheet_name='Hoja_uno')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.

Verificar el cambio abriendo el archivo desde drive